config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_up' => 'devise/registrations#new'
    post 'admin' => 'devise/registrations#create'
    get 'admin/sign_in' => 'admin/devise/sessions#new'
    post 'admin/sign_in' => 'admin/devise/sessions#create'
    delete 'admin/sign_out' => 'devise/sessions#destroy'
    post 'admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "items#top"

      resources :items, only: [:top, :index, :show]
      resources :addresses, only: [:index, :create, :edit, :update]
      delete '/addresses/:id' => 'addresses#destroy', as: 'destroy_address'

      get '/customers/:id' => 'customers#show'
      resources :customers, only: [:edit, :update] do
        member do #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
            get "unsubscribe"
            #ユーザーの会員状況を取得
            patch "withdrawl"
            #ユーザーの会員状況を更新
        end
      end


      resources :orders, only: [:index, :create, :show, :new]
      get '/order/confirm' => 'orders#confirm', as: 'order_confirm'
      get '/complete' => 'orders#complete', as: 'order_complete'


      resources :cart_items, only: [:index, :create, :destroy, :update]
      delete :cart_items, to: 'cart_items#destroy_all'

    namespace :admin do
      resources :items, only: [:index, :new, :create, :show,  :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update] do
        resources :order_details, only: [:update]
      end
      resources :customers, only: [:index, :show,  :edit, :update]
    end
    
    get '/admin/top' => 'admin#top'


    get '/about' => 'abouts#top'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
		"#{self.postal_code} #{self.address} #{self.name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
	belongs_to :item
	
  def price
    item.price * amount * 1.1
  end
	
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy       
  
  enum is_deleted: {Available: true, Invalid: false} #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
    #有効会員はtrue、退会済み会員はfalse

    def active_for_authentication?
        super && (self.is_deleted === "Available")
    end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  has_many :cart_items
	has_many :order_details
	has_many :orders, through: :order_details
	belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
	has_many :items, through: :order_details
	accepts_nested_attributes_for :order_details
	belongs_to :customer

	#enaum_支払方法
	enum payment_method: {クレジットカード:1, 銀行振込:2}

	#注文ステータス
	enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 
  belongs_to :item
  belongs_to :order

  enum making_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def top
    @orders = Order.created_today
  	@count = @orders.count
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @genres = Genre.all
    @items = Item.all
  end

  def top
    @genres = Genre.all
    @items = Item.all
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
		@cart_item = CartItem.new(item_id: @item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image_id, :introduction)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/top.html.erb
<%= render "layouts/adminheader" %>

<div class="row" style="width: 90%; margin: 20px auto;">
	<h1>
  	<span>本日の注文件数　　　</span>
   		<%=link_to admin_orders_path(day: 1) do%>
  			<%= @count %>
  		<% end %>
  	<span>件</span>
	</h1>
</div>

app/views/layouts/_adminheader.html.erb
<html>
  <head>
    <title>Nagano_CAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  
  
  
  <body>
    
    <% if flash[:notice] %>
      <div class="notihication is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notihication is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

  <div class="header">
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="row">
          <div class="col-xs-3">
            <h2 class="navbar-header">LOGO</h2>
          </div>
          <div class="col-xs-9">
            <div id="slidemenu">
              <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                <% if admin_signed_in? %>
                  <li class="">
                      <%= link_to "商品一覧", admin_items_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                  <li class="">
                      <%= link_to "会員一覧", admin_customers_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "注文履歴一覧", admin_orders_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "ジャンル一覧", admin_genres_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "ログアウト", admin_sign_out_path, method: :destroy, class: "navbar-item button is-warning is-light" %>
                  </li>
                <% else %>
                  <li class="">
                      <%= link_to 'About', about_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "商品一覧", items_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                    　<%= link_to "新規登録", new_customer_registration_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "ログイン", new_customer_session_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
    
  <%= yield %>
    <footer class="footer">
    </footer>
  </body>
</html>

app/views/layouts/_header.html.erb
<html>
  <head>
    <title>Nagano_CAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  
  
  
  <body>
    
    <% if flash[:notice] %>
      <div class="notihication is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notihication is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

  <div class="header">
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="row">
          <div class="col-xs-3">
            <h2 class="navbar-header">
              <%= link_to root_path do %>
                LOGO
              <% end %>
            </h2>
          </div>
          <div class="col-xs-9">
            <div id="slidemenu">
              <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                <% if customer_signed_in? %>
                  <li class="">
                    <p>ようこそ、<%= current_customer.last_name %>さん！</p>
                  </li>
                  <li class="">
                      <%= link_to "マイページ", customer_path(current_customer), class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "商品一覧", items_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "カート", cart_items_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "navbar-item button is-warning is-light" %>
                  </li>
                <% else %>
                  <li class="">
                      <%= link_to 'About', about_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "商品一覧", items_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                    　<%= link_to "新規登録", new_customer_registration_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                  <li class="">
                      <%= link_to "ログイン", new_customer_session_path, class: "navbar-item button is-warning is-light" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
    
  <%= yield %>
    <footer class="footer">
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>