config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_up' => 'devise/registrations#new'
    post 'admin' => 'devise/registrations#create'
    get 'admin/sign_in' => 'admin/devise/sessions#new'
    post 'admin/sign_in' => 'admin/devise/sessions#create'
    delete 'admin/sign_out' => 'devise/sessions#destroy'
    post 'admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "items#top"

      resources :items, only: [:top, :index, :show]
      resources :addresses, only: [:index, :create, :edit, :update]
      delete '/addresses/:id' => 'addresses#destroy', as: 'destroy_address'

      get '/customers/:id' => 'customers#show'
      resources :customers, only: [:edit, :update] do
        member do #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
            get "unsubscribe"
            #ユーザーの会員状況を取得
            patch "withdrawl"
            #ユーザーの会員状況を更新
        end
      end


      resources :orders, only: [:index, :create, :show, :new]
      get '/order/confirm' => 'orders#confirm', as: 'order_confirm'
      get '/complete' => 'orders#complete', as: 'order_complete'


      resources :cart_items, only: [:index, :create, :destroy, :update]
      delete :cart_items, to: 'cart_items#destroy_all'

    namespace :admin do
      resources :items, only: [:index, :new, :create, :show,  :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update] do
        resources :order_details, only: [:update]
      end
      resources :customers, only: [:index, :show,  :edit, :update]
    end
    
    get '/admin/top' => 'admin#top'


    get '/about' => 'abouts#top'

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
	has_many :items, through: :order_details
	accepts_nested_attributes_for :order_details
	belongs_to :customer

	#enaum_支払方法
	enum payment_method: {クレジットカード:1, 銀行振込:2}

	#注文ステータス
	enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  	   @orders = Order.all
  end

  def show
  	@order = Order.find(params[:id])
  	#@order_details = @order.order_details
  end

  def update
#orderのdeposit_statusの更新
  	@order = Order.find(params[:id])
    @order.update(order_params)
    flash[:success] = "更新に成功しました"
  	if @order.status == "入金確認"
  	   @order.order_details.each do |order_detail|
  	   #order_detail.making_status = "製作待ち"
  	   order_detail.update(making_status: 1)

  	   end
  	end
  	redirect_to admin_orders_path
  end

  private
  def order_params
  	params.require(:order).permit(:status, order_details_attributes:[:id, :making_status])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
		@customer = current_customer
	  #cartが空の場合、cart_items#indexに戻される
		if @customer.cart_items.blank?
 		   flash[:warning] = "カートが空です"
			 redirect_to cart_items_path
		else
			@order = Order.new(customer_id: @customer.id)
			@addresses = @customer.addresses
			@address = Address.new(customer_id: @customer.id)
		end
  end

  def confirm
    @order = Order.new(order_params)
    if params[:order][:address_select] == "ご自身の住所"
       @order.postal_code = current_customer.postal_code
       @order.address = current_customer.address
       @order.name = "#{current_customer.last_name}" + "#{current_customer.first_name}"
    elsif params[:order][:address_select] == "登録済住所から選択"
          address = Address.find(params[:address_info][:address_id])
          @order.address = address.address
          @order.name = address.name
          @order.postal_code = address.postal_code
    elsif params[:order][:address_select] == "新しいお届け先"
          @order.postal_code = params[:order][:postal_code]
          @order.address = params[:order][:address]
          @order.name = params[:order][:name]
    end

    if params[:order][:payment_method] == "クレジットカード"
       @order.payment_method = "クレジットカード"
    elsif params[:order][:payment_method] == "銀行振込"
          @order.payment_method = "銀行振込"
    end
      @cart_items = current_customer.cart_items
      @sum = 0
  end

# 情報の保存
  def create
  	@order = Order.new(order_params)
  	@order.customer_id = current_customer.id
  	@customer = current_customer
  	@order.save

    current_customer.cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = @order.id
      order_detail.item_id = cart_item.item.id
      order_detail.amount = cart_item.amount
      order_detail.pay = order_detail.amount * order_detail.item.price
      order_detail.save
      cart_item.destroy
    end

    redirect_to order_complete_path
  end

# 注文完了画面(カートを空にする)
  def complete

  end

  def index
		@customer = current_customer
		@orders = @customer.orders
	#他のuserのアクセス阻止
		#unless current_user.nil? || current_user.id == @user.id
    #flash[:warning] = "アクセス権がありません"
		  #redirect_to orders_path(id: current_user.id)
    #end
  end


  def show
  	@order = Order.find(params[:id])
  end

	private
#ストロングパラメーター
	def order_params
	 params.require(:order).permit(
	 	:customer_id, :payment_method, :address, :postal_code, :name
	 	)
	end

#退会済みユーザーへの対応
  def user_is_deleted
    if user_signed_in? && current_user.is_deleted?
       redirect_to root_path
    end
  end

#adminでなければuserの中で振り分ける
  def authenticate!
    if admin_signed_in?
    else
    	authenticate_user!
    end
  end

#ordersと直打ちした場合
  def params_check
  	if params[:id].nil?
  		redirect_to root_path
  	end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<%= render "layouts/adminheader" %>

<div class="row" style="width:60%; margin:0 auto;">
<h4>注文履歴一覧画面</h4>

  <table class="table table-bordered">
  	<tr>
  		<th>購入日時</th>
  		<th>購入者</th>
  		<th>注文個数</th>
  		<th>ステータス</th>
  	</tr>

    <% @orders.each do |order| %>
  	<tr>
  	  <td><%= link_to order[:created_at].strftime("%Y-%m-%d %H:%M"), admin_order_path(order) %></td>
  		<td><%= order.customer.last_name %><%= order.customer.first_name %></td>
  		<td><%= order.order_details.sum(:amount) %></td>
  		<td><%= order.status %></td>

  	 </tr>
    <% end %>
  </table>
</div>

app/views/admin/orders/show.html.erb
<%= render "layouts/adminheader" %>

  <div class="row" style="width:60%; margin:0 auto;">
	<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">注文詳細画面</h4>
	<table class="table table-bordered">
	  <tr>
		<th>購入者</th>
		<td><%= link_to  admin_customer_path(@order.id) do %>
	  			<%= @order.customer.last_name %>
	  			<%= @order.customer.first_name %>
				<% end %>
	    </td>
	  </tr>
	  <tr>
		<th>配送先</th>
		<td><%= @order.postal_code %>
				<%= @order.address %>
				<br>
				<%= @order.name %>
		</td>
	  </tr>

	  <tr>
		<th>支払方法</th>
		<td><%= @order.payment_method %></td>
	  </tr>
	  <tr>
		<th>注文ステータス</th>
		<td>
			<%= form_with model:@order, url:admin_order_path(@order.id), local:true, method: :patch do |f| %>
			  <%= f.select :status, [["入金待ち","入金待ち"], ["入金確認","入金確認"], ["製作中","製作中"], ["発送準備中","発送準備中"], ["発送済み","発送済み"]] %>
			  <div class="Update">
		      <%= f.submit "変更" %>
		    </div>
			<% end %>
		</td>
	  </tr>
	</table>

<%#= form_with model:@order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
	  <%#= f.fields_for :order_details do |i| %>
	<table class="table table-bordered">
	  <tr>
			<th>商品名</th>
			<th>単価(税込)</th>
			<th>数量</th>
			<th>小計</th>
			<th>製作ステータス</th>
			<th></th>
	  </tr>

    <% @order.order_details.each do |order_detail| %>
	  <tr>
	    <td><%= order_detail.item.name %></td>
			<td><%= (order_detail.item.price * 1.1).round %></td>
			<td><%= order_detail.amount %></td>
		  <td><%= ((order_detail.item.price * order_detail.amount * 1.1).round(2)).ceil %>円</td>
		  <td>
		  	<%= form_with model: order_detail, url: admin_order_order_detail_path(@order.id, order_detail.id), local: true, method: :patch do |f| %>
		  	<%#= form_with model:@order_detail, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
	        <%#= f.fields_for :order_details do |i| %>
			  	  <%#= f.select :making_status, OrderDetail.making_statuses.keys.map[|k| k] %>
			  	  <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a, {} %>
			  	  <%#= f.select :making_status, [["製作不可","製作不可"], ["製作待ち","製作待ち"], ["製作中","製作中"], ["製作完了","製作完了"]] %>
			      <%= f.submit '更新', class:"btn btn-success" %>
			    <%# end %>
			  <% end %>
		  </td>
		</tr>
		      <%#= i.select :status, OrdereDetail.item_statuses.keys.map{ |l| l } %>
						<%# case i.object.product_status when "製作待ち" %>
								<!-- span class="badge" style="background: red;"><%#= i.object.product_status %></span -->
								<%# when "製作中" %>
									<!-- span class="badge" style="background: green;"><%#= i.object.product_status %></span -->
								<%# when "製作完了" %>
									<!-- span class="badge" style="background: blue;"><%#= i.object.product_status %></span -->
								<%# end %>
	  <% end %>
	</table>


	<table class="table table-bordered">
		<tr>
			<th>商品合計</th>
			<td>
      	<% @sum = 0 %>
        <% @order.order_details.each do |order_detail| %>
	      <% @sum += order_detail.pay %>
        <% end %>
        <%= ((@sum * 1.1).round(2)).ceil %>
        円
      </td>
     </tr>
     <tr>
			<th>配送料</th>
			<td>500円</td>
		</tr>
		<tr>
			<th>請求金額合計</th>
			<td><%= (((@sum * 1.1).round(2)).ceil) + 500 %>円</td>
	  </tr>
	</table>
</div>