config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_up' => 'devise/registrations#new'
    post 'admin' => 'devise/registrations#create'
    get 'admin/sign_in' => 'admin/devise/sessions#new'
    post 'admin/sign_in' => 'admin/devise/sessions#create'
    delete 'admin/sign_out' => 'devise/sessions#destroy'
    post 'admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "items#top"

      resources :items, only: [:top, :index, :show]
      resources :addresses, only: [:index, :create, :edit, :update]
      delete '/addresses/:id' => 'addresses#destroy', as: 'destroy_address'

      get '/customers/:id' => 'customers#show'
      resources :customers, only: [:edit, :update] do
        member do #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
            get "unsubscribe"
            #ユーザーの会員状況を取得
            patch "withdrawl"
            #ユーザーの会員状況を更新
        end
      end


      resources :orders, only: [:index, :create, :show, :new]
      get '/order/confirm' => 'orders#confirm', as: 'order_confirm'
      get '/complete' => 'orders#complete', as: 'order_complete'


      resources :cart_items, only: [:index, :create, :destroy, :update]
      delete :cart_items, to: 'cart_items#destroy_all'

    namespace :admin do
      resources :items, only: [:index, :new, :create, :show,  :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update] do
        resources :order_details, only: [:update]
      end
      resources :customers, only: [:index, :show,  :edit, :update]
    end
    
    get '/admin/top' => 'admin#top'


    get '/about' => 'abouts#top'

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy       
  
  enum is_deleted: {Available: true, Invalid: false} #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
    #有効会員はtrue、退会済み会員はfalse

    def active_for_authentication?
        super && (self.is_deleted === "Available")
    end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path(@customer)
  end
  
  def withdrawl
    @customer = Customer.find(current_customer.id)
    #現在ログインしているユーザーを@userに格納
    @customer.update(is_deleted: "true")
    #updateで登録情報をInvalidに変更
    reset_session
    #sessionIDのresetを行う
    redirect_to root_path
    #指定されたrootへのpath
  end

  private
  # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_deleted)
  end

  
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def show
    @customer = current_customer
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to '/customers/my_page'
  end

  def unsubscribe
    @customer = current_customer
    #ユーザーの情報を見つける
  end

  def withdrawl
    @customer = Customer.find(current_customer.id)
    #現在ログインしているユーザーを@userに格納
    @customer.update(is_deleted: "Invalid")
    #updateで登録情報をInvalidに変更
    reset_session
    #sessionIDのresetを行う
    redirect_to root_path
    #指定されたrootへのpath
  end

  #@customer = Customer.find(params[:id])

  	#if  @customer.is_deleted?
  		  #@customer.is_deleted = false
  	#else
  		  #@customer.is_deleted = true
  	#end
        #@customer.save
        #redirect_to edit_admin_customer_path(@customer)
  #end


  private
  # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
 <%= render "layouts/header" %>

<div class="container">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-2">
      <div style="background-color:#EAEEEF; width:150px; padding:0.1px" >
        <div class="text-center">
          <h5>登録情報編集</h5>
        </div>
      </div>
    </div>
    <div class="col-lg-7">
    </div>
  </div>


  <%= form_with model:@customer, local:true, method: :patch do |f| %>
    <form class="form-horizontal">
    	<div class="form-group">
    	  <div class="row">
          <label class="col-lg-2 control-label" for="name">名前</label>
          <div class="col-lg-3">
            <%= f.label :last_name,"(姓)" %> <%= f.text_field :last_name, autofocus: true %>
          </div>
          <div class="col-lg-3">
            <%= f.label :first_name,"(名)" %> <%= f.text_field :first_name, autofocus: true %>
          </div>
          <div class="col-lg-4">
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="row">
          <label class="col-lg-2 control-label" for="name_kana">フリガナ</label>
          <div class="col-lg-3">
            <%= f.label :last_name_kana,"(セイ)" %> <%= f.text_field :last_name_kana, autofocus: true %>
          </div>
          <div class="col-lg-3">
            <%= f.label :first_name_kana,"(メイ)" %> <%= f.text_field :first_name_kana, autofocus: true %>
          </div>
          <div class="col-lg-4">
          </div>
        </div>
      </div>
    
      <div class="form-group">
        <div class="row">
          <label class="col-sm-2 control-label" for="email">メールアドレス</label>
          <div class="col-sm-3">
            <%= f.text_field :email, autofocus: true, autocomplete: "email" %>
          </div>
          <div class="col-lg-7">
          </div>
        </div>
      </div>
    
      <div class="form-group">
        <div class="row">
          <label class="col-lg-2 control-label" for="postcode">郵便番号(ハイフンなし)</label>
          <div class="col-lg-3">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
          </div>
          <div class="col-lg-7">
          </div>
        </div>
      </div>
    
      <div class="form-group">
        <div class="row">
          <label class="col-lg-2 control-label" for="address">住所</label>
          <div class="col-lg-10">
             <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
          </div>
          <div class="col-lg-7">
          </div>
        </div>
      </div>
    
      <div class="form-group">
        <div class="row">
          <label class="col-lg-2 control-label" for="phone_number">電話番号(ハイフンなし)</label>
          <div class="col-lg-5">
            <%= f.number_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
          </div>
          <div class="col-lg-7">
          </div>
        </div>
      </div>
    
      <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-lg-4">
          <div class="Update">
            <%= f.submit "編集内容を保存する" %>
          </div>
        </div>
      <% end %>
        <div class="col-lg-6">
          <div class="withdrawl"> <!-- https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2 -->
            <%= link_to "退会する", "/customers/:id/unsubscribe" %>
          </div>
        </div>
      </div>
    </form>
  
  
</div>

app/views/customers/show.html.erb
 <%= render "layouts/header" %>

<div class="container">  <!-- この行を追加 -->
  <div class="row">      <!-- この行を追加 -->
    <div class="col-lg-6">
      <div style="background-color:#EAEEEF; width:180px; padding:5px" >
        <div class="text-center">
          <h4>マイページ</h4>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
    </div>
  </div>
    
  <div class="row">
    <div class="session_info">
      <div class="col-lg-2">
        <h4>登録情報</h4>
      </div>
      <div class="col-lg-1">
        <%= link_to  edit_customer_path(@customer.id) do %>
          <button class="btn btn-info">編集する</button>
        <% end %>
      </div>
      <div class="col-lg-2">
        <%= link_to  edit_customer_registration_path(@customer.id) do %> <!-- https://qiita.com/anraku/items/3d7d675925de81b825d4, https://qiita.com/katryo/items/b3ee01758bbe72fb764d -->
          <button class="btn btn-info">パスワードを変更する</button>
        <% end %>
      </div>
      <div class="col-lg-7">
      </div>
    </div>
  </div>

  <table class="table table-bordered">
    <tbody>
  		<tr>
  			<th>氏名</th>
  			<td><%= @customer.last_name %> <%= @customer.first_name %></td>
  		</tr>
  		<tr>
  			<th>カナ</th>
  			<td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
  		</tr>
  		<tr>
  			<th>郵便番号</th>
  			<td><%= @customer.postal_code %></td>
  		</tr>
  		<tr>
  			<th>住所</th>
  			<td><%= @customer.address %></td>
  		</tr>
  		<tr>
  			<th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
  		</tr>
  		<tr>
  			<th>メールアドレス</th>
  			<td><%= @customer.email %></td>
  		</tr>
  	</tbody>
  </table>
      
  <div class="row">
    <div class="col-lg-1">
      <div class="address_index">
        <h4>配送先</h4>
      </div>
    </div>
    <div class="col-lg-2">
      <%= link_to  addresses_path do %>
        <button class="btn btn-info">一覧を見る</button>
      <% end %>
    </div>
    <div class="col-lg-9">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-1">
      <div class="order_index">
        <h4>注文履歴</h4>
      </div>
    </div>
    <div class="col-lg-2">
        <%= link_to  orders_path do %>
          <button class="btn btn-info">一覧を見る</button>
        <% end %>
      </div>
      <div class="col-lg-9">
      </div>
    </div>
  </div>
</div>

app/views/customers/unsubscribe.html.erb
<%= render "layouts/header" %>


<h3 class="text-center">
  <strong>本当に退会しますか？</strong><br>
  <br></br>
退会すると、会員登録情報や<br>
これまでの購入履歴が閲覧できなくなります。<br>
退会する場合は、「退会する」をクリックしてください。
</h3>

<div class="container">
  <div class="row"> 
    <div class="col-lg-4">
    </div>
    <div class="col-lg-2">
      <div class="mypage">
        <h4 class="text-center">
          <%= link_to customer_path(@customer.id) do %>
            <%= "退会しない" %>
          <% end %>
        </h4>
      </div>
    </div>
    <div class="col-lg-2">
      <div class="withdrawl">
        <h4 class="text-center">
          <%= link_to "退会する", "/customers/:id/withdrawl", method: :patch, data: { confirm: "本当に退会してもよろしいですか？"}  %>
          <%#= form_with model:@customer, withdrawl_customer_path(@customer.id), method: :patch, local:true do |f| %>
				    <%#= f.submit '退会する' %>
			    <%# end %>
          
        </h4>
      </div>
    </div>
    <div class="col-lg-4">
    </div>
  </div>
</div>