config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_up' => 'devise/registrations#new'
    post 'admin' => 'devise/registrations#create'
    get 'admin/sign_in' => 'admin/devise/sessions#new'
    post 'admin/sign_in' => 'admin/devise/sessions#create'
    delete 'admin/sign_out' => 'devise/sessions#destroy'
    post 'admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "items#top"

      resources :items, only: [:top, :index, :show]
      resources :addresses, only: [:index, :create, :edit, :update]
      delete '/addresses/:id' => 'addresses#destroy', as: 'destroy_address'

      get '/customers/:id' => 'customers#show'
      resources :customers, only: [:edit, :update] do
        member do #https://qiita.com/tt_tsutsumi/items/588d0e65a289a15530d2
            get "unsubscribe"
            #ユーザーの会員状況を取得
            patch "withdrawl"
            #ユーザーの会員状況を更新
        end
      end


      resources :orders, only: [:index, :create, :show, :new]
      get '/order/confirm' => 'orders#confirm', as: 'order_confirm'
      get '/complete' => 'orders#complete', as: 'order_complete'


      resources :cart_items, only: [:index, :create, :destroy, :update]
      delete :cart_items, to: 'cart_items#destroy_all'

    namespace :admin do
      resources :items, only: [:index, :new, :create, :show,  :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update] do
        resources :order_details, only: [:update]
      end
      resources :customers, only: [:index, :show,  :edit, :update]
    end
    
    get '/admin/top' => 'admin#top'


    get '/about' => 'abouts#top'

end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  has_many :cart_items
	has_many :order_details
	has_many :orders, through: :order_details
	belongs_to :genre
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!


  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @genres = Genre.all
    @items = Item.all
  end

  def top
    @genres = Genre.all
    @items = Item.all
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
		@cart_item = CartItem.new(item_id: @item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image_id, :introduction)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
 <%= render "layouts/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <div class="row">
        <div class="col-lg-2">
          <div class="genre_style">
            <div class="genre_title">
              <h4>ジャンル検索</h4>
            </div>
            <if genre.status == true>
            <div class="genre_contents">
              <% @genres.each do |genre| %> <!-- https://web-camp.io/magazine/archives/18333 -->
                <div class="genre-list">
                  <%= link_to root_path(genre: genre.id) do %>
                    <%= genre.name %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-lg-10">
          <h2 class="title">商品一覧</h2> <h4>全<%#= items.count %>件</h4>
          
          <div class="row">
            <div class="col-lg-12">
              <section class="section">
                <div class="list-wrap">
                  <% @items.each do |item| %>
                    <div class="item-box">
                      <%= link_to item_path(item) do %>
                        <%= attachment_image_tag item, :image, :fill, 150, 110, format: 'jpeg' %>
                      <% end %>
                        <div class="name">
                          <span class="item-name"><strong>商品名</strong>　<%= item.name %></span>
                        </div>
                        <div class="price">
                          <span class="item-price"><strong>￥</strong>　<%= ((item.price * 1.1).round(2)).ceil %></span>
                        </div>
                    </div>
                  <% end %>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/show.html.erb
 <%= render "layouts/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <div class="row">
        <div class="col-lg-2">
          <div class="genre_style">
            <div class="genre_title">
              <h4>ジャンル検索</h4>
            </div>
            <if genre.status == true>
            <div class="genre_contents">
              <% @genres.each do |genre| %> <!-- https://web-camp.io/magazine/archives/18333 -->
                <div class="genre-list">
                  <%= link_to root_path(genre: genre.id) do %>
                    <%= genre.name %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        
        <div class="col-lg-1">
        </div>
        
        <div class="col-lg-9">
          <div class="row">
            <div class="col-lg-5">
              <%= attachment_image_tag @item, :image, :fill, 300, 200, format: 'jpeg' %>
            </div>
            <div class="col-lg-7">
              <h2 class="item_title"><strong><%= @item.name %></strong></h2>
              <p><%= @item.introduction %></p>
              <span class="item-price">
                <h4>￥<%= ((@item.price * 1.1).round(2)).ceil %>
                <span>(税込)</span>
                </h4>
              </span>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-9">
            </div>
              <%= form_with model: @cart_item, local:true do |f| %>
          		<%= f.hidden_field :item_id %>
          	<div class="col-lg-1">
          		<%= f.select :amount, [1,2,3,4,5,6,7,8,9,10] %>
            </div>
            <div class="col-lg-2">
          		<%= f.submit "カートに入れる", class: 'btn btn-primary' %>
          	</div>
          	<% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/top.html.erb
 <%= render "layouts/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <div class="row">
        <div class="col-lg-2">
          <div class="genre_style">
            <div class="genre_title">
              <h4>ジャンル検索</h4>
            </div>
            <if genre.status == true>
            <div class="genre_contents">
              <% @genres.each do |genre| %> <!-- https://web-camp.io/magazine/archives/18333 -->
                <div class="genre-list">
                  <%= link_to root_path(genre: genre.id) do %>
                    <%= genre.name %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        
    <div class="col-lg-10">
      <div class="row">
        <div class="col-lg-9">
              <h4 class="text-center">
              ようこそ、NaganoCakeへ！<br>
              このサイトは、ケーキ販売のECサイトになります。<br>
              会員でない方も商品の閲覧はできますが、<br>
              購入には会員登録が必要になります。
              </h4>
        </div>
        <div class="col-lg-3">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3">
          <h3><strong>オススメ商品</strong></h3>
        </div>
        <div class="col-lg-9">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <section class="section">
            <div class="list-wrap">
                  <% @items.each do |item| %>
                    <div class="item-box">
                      <%= link_to item_path(item) do %>
                        <%= attachment_image_tag item, :image, :fill, 150, 110, format: 'jpeg' %>
                      <% end %>
                        <div class="name">
                          <span class="item-name"><strong>商品名</strong>　<%= item.name %></span>
                        </div>
                        <div class="price">
                          <span class="item-price"><strong>￥</strong>　<%= item.price %></span>
                        </div>
                    </div>
                  <% end %>
            </div>
          </section>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10">
        </div>
        <div class="col-lg-2">
          <%= link_to "もっと見る＞", items_path %>
        </div>
      </div>
    </div>
  </div>
</section>  
      